version: '3.9'

services:

  whisper:
    stdin_open: true
    tty: true
    image: dleongsh/whisper:1.10.0-cuda11.3-v2
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - /mnt/c/projects/whisper:/whisper
      - /mnt/c/projects/whisper_models:/root/.cache/whisper
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 16gb
    working_dir: /whisper
